Integrate string-similarity into a function as deprecated
NamelessMC/NamelessBot pull request #20
Opened 2023-07-12 11:27 UTC by PadowYT2

2023-07-12 14:56 UTC, tadhgboyle requested changes
Not sure that pulling an abandoned libraries code into our codebase is a great solution here - it puts the responsibility of maintaining this (complex) code on us. The package is still working fine even though it's not maintained anymore (because it does 1 thing and it does that thing well, there is no need for it to get updated) - I don't personally see any point in doing this

2023-07-14 09:44 UTC, PadowYT2 commented
> Not sure that pulling an abandoned libraries code into our codebase is a great solution here - it puts the responsibility of maintaining this (complex) code on us. The package is still working fine even though it's not maintained anymore (because it does 1 thing and it does that thing well, there is no need for it to get updated) - I don't personally see any point in doing this

Well as the package is depcreated, why use it and not just integrate it within the code? You don't need to mantain the code as the code hasn't be touched for years and works fine. Also Super himself wanted to do it "later"
![1](https://cdn.padow.ru/0kjR4)

2023-07-14 16:45 UTC, samerton commented
I agree with aber here - I don't think copying the code into our codebase is the best thing to do. I see the following options:

1. We create our own implementation from scratch
2. We fork the deprecated package and maintain it ourselves in a new repository
3. We find an alternative library
4. We continue to use the deprecated library

2023-07-15 09:21 UTC, PadowYT2 commented
> I agree with aber here - I don't think copying the code into our codebase is the best thing to do. I see the following options:
> 
> 1. We create our own implementation from scratch
> 2. We fork the deprecated package and maintain it ourselves in a new repository
> 3. We find an alternative library
> 4. We continue to use the deprecated library

There's an alternative - https://www.npmjs.com/package/string-similarity-js, seems good and even less [code](https://github.com/stephenjjbrown/string-similarity-js/blob/master/src/string-similarity.ts)

2023-08-31 10:44 UTC, supercrafter100 approved these changes
lgtm

2023-08-31 10:45 UTC, supercrafter100 commented
Awaiting Aber's review on this one as well

2024-02-28 08:41 UTC, PadowYT2 commented
👀

2026-05-21 06:56 UTC, closed without merging